# Generated by Django 4.2 on 2023-04-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_alter_warehouse_options_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='Цена')),
                ('status', models.CharField(choices=[('created', 'Yaratilgan'), ('accepted', 'Tasdiqlangan'), ('completed', 'Tugallangan'), ('canceled', 'Rad etilgan')], max_length=255, verbose_name='Статус')),
                ('income_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Импортированный товар',
                'verbose_name_plural': 'Импортированные товары',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('phone', models.CharField(max_length=16)),
                ('info', models.TextField(verbose_name='Provider haqida malumot')),
            ],
            options={
                'verbose_name': 'Провайдер',
                'verbose_name_plural': 'Провайдеры',
            },
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Jami Summa')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Jami Mahsulotlar soni')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers.income')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers.provider'),
        ),
        migrations.AddField(
            model_name='income',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
        ),
    ]
