# Generated by Django 4.2 on 2023-04-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ware House',
                'verbose_name_plural': 'Ware Houses',
            },
        ),
        migrations.CreateModel(
            name='WareHouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Jami Summa')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Jami Mahsulotlar soni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Ware House Product',
                'verbose_name_plural': 'Ware House Products',
            },
        ),
    ]
